### ISSUE TITLE
Does it make sense to introduce the concept of an event completing

### ISSUE THREAD

**Issue by designfrontier** [ansble/Action#17]
https://www.youtube.com/watch?v=FAZJsxcykPs&index=2&list=PLfXiENmg6yyU5kEHyo1kYkq7HEzBOoiTT

Does it make sense to give events the ability to complete themselves by unsubscribing when they are done? This makes sense from performance standpoint, and sort of from a theoretical standpoint. Moves us a little more towards the ideas of reactive programming and observables though still with a slightly different flavor.

@uniqname @mrGrigg @mjgyesme

**Comment by uniqname** [comment]
You mean like a listenOnce?

—

**Comment by designfrontier** [comment]
No... I mean more like the data producer can notify the listener that it is no longer needed. Part of an observable in reactive programming

**Comment by uniqname** [comment]
Not sure I understand. You can dumbsplain it to me on Monday. :)

On Fri, Dec 12, 2014 at 5:23 PM, Daniel Sellers notifications@github.com
wrote:

> No... I mean more like the data producer can notify the listener that it
> is no longer needed. Part of an observable in reactive programming
> 
> > On Dec 12, 2014, at 4:58 PM, Cory notifications@github.com wrote:
> > 
> > You mean like a listenOnce?
> > 
> > —
> > Sent from Mailbox
> > 
> > On Fri, Dec 12, 2014 at 4:33 PM, Daniel Sellers <
> > notifications@github.com>
> > wrote:
> > 
> > > https://www.youtube.com/watch?v=FAZJsxcykPs&index=2&list=PLfXiENmg6yyU5kEHyo1kYkq7HEzBOoiTT
> > > Does it make sense to give events the ability to complete themselves
> > > by unsubscribing when they are done? This makes sense from performance
> > > standpoint, and sort of from a theoretical standpoint. Moves us a little
> > > more towards the ideas of reactive programming and observables though still
> > > with a slightly different flavor.
> > > 
> > > ## @uniqname @mrGrigg @mjgyesme
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/designfrontier/Action/issues/17
> > > —
> > > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/designfrontier/Action/issues/17#issuecomment-66855508
> .

## 

Cory Brown

**Comment by designfrontier** [comment]
@uniqname does it make more sense having watched that video?

**Comment by uniqname** [comment]
Yes. Much.

On Sat, Dec 13, 2014 at 9:54 AM, Daniel Sellers notifications@github.com
wrote:

> @uniqname https://github.com/uniqname does it make more sense having
> watched that video?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/designfrontier/Action/issues/17#issuecomment-66882683
> .

## 

Cory Brown

**Comment by designfrontier** [comment]
After further discussion and talking with @uniqname this morning this feature really would be a convenience and can be handled with pure events. So we won't be adding it to the framework.
